platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'


target 'HenriMobileInterviewProject' do
  # Pods for HenriMobileInterviewProject
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'HenriMobileInterviewProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'HenriMobileInterviewProject-tvOS' do
  # Pods for HenriMobileInterviewProject-tvOS

  target 'HenriMobileInterviewProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
